#!/usr/bin/env php
<?php
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;
use Illuminate\Foundation\Application;
use Illuminate\Foundation\Console\Kernel;
if (file_exists($autoload = __DIR__.'/vendor/autoload.php')) require $autoload;
else { fwrite(STDERR,"Composer dependencies are not installed. Run: composer install\n"); exit(1); }
$app = require_once __DIR__.'/bootstrap/app.php';
$status = $app->handleCommand(new ArgvInput, new ConsoleOutput);
exit($status);
